### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by NovaXCIV** [Greek/ToggleNametags#1]
Can you add the possibility to disable only players nametags? (but not from mobs or other entities)

**Comment by Greek** [comment]
Yep! I'll get to work on a config system ASAP and add this along with this system

**Comment by Greek** [comment]
Hey there! You can now toggle this using `/toggleothernametags` command. I will push the update to Modrinth right now.

**Comment by Greek** [comment]
Added in [1.2 release](https://modrinth.com/mod/hidetags/version/1.2). Please note that this update does NOT hide armor stand entity labels.
