### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Cirinmoran** [Greek/ToggleNametags#2]
Hello! Thank you for creating this unique mods in the new version of Minecraft. but when I used this mod, I found that it didn't completely hide the name tag (the name tag would appear whenever a block blocked my view, but the name tag would only disappear if I looked at the player)
![录制_2022_05_18_16_28_53_717](https://user-images.githubusercontent.com/89350770/168995199-f1814d5d-bd59-4680-9962-02e1e87f445c.gif)

**Comment by Greek** [comment]
Thanks for the report! I couldn't reproduce this issue with a similar environment. Could you try to reproduce this without any other mods?

**Comment by Cirinmoran** [comment]
After my testing, I found a conflict between your mods and EntityCulling, as long as I remove EntityCulling, ToggleNametags will work fine (completely hide name tags)
[https://www.curseforge.com/minecraft/mc-mods/entityculling](url)

**Comment by Greek** [comment]
Thanks for confirming this. I can't really do anything about this conflict unfortunately.
