### ISSUE TITLE
Need to enable every time I start

### ISSUE THREAD

**Issue by MrBeat93** [Greek/ToggleNametags#9]
Every time I join a server I need to toggle the setting to hide the player name. It seems like it does not read the config file. 
I have the setting true in the file but its like its always load it as false every time I start Minecraft. 

render_all_except_players=true

**Comment by Greek** [comment]
Thanks! I've noticed this before too but I never got around to fixing it. I'll draft up something before the 1.21 release.

**Comment by MrBeat93** [comment]
> Thanks! I've noticed this before too but I never got around to fixing it. I'll draft up something before the 1.21 release.

Nice and sry, I forgot to mention that I used the Minecraft version 1.20.1

**Comment by Greek** [comment]
Should be fixed now. You can download the latest version of the mod [here](https://github.com/Greek/ToggleNametags/actions/runs/11321849964/artifacts/2051608242), or on Modrinth 😄
